# Generated by Django 4.0.5 on 2022-06-13 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
