# Generated by Django 4.0.5 on 2022-06-13 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_remove_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
